# Generated by Django 4.1.1 on 2023-02-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('property_type', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('other_info', models.TextField(auto_created=None, max_length=300)),
            ],
        ),
    ]
