# Generated by Django 4.1.1 on 2023-02-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query_model',
            name='other_info',
            field=models.TextField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='query_model',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
