# Generated by Django 4.1.1 on 2023-02-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_contact_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_model',
            name='other_info',
            field=models.TextField(default='None', max_length=300),
        ),
    ]
